name: "Build Android App"
run-name: ${{ github.actor }} is learning build Android App using Github Actions
on:
  push:
    branches:
      - dev-release
  pull_request:
    branches:
      - develop-uat
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "20"
          distribution: "adopt"
          cache: "gradle"

      - name: Change wrapper permissions
        run: chmod +x ./android/gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Run Yarn Install
        run: |
          npm install --force

      - name: Build App
        run: |
          cd ./android
          ./gradlew assembleDebug

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./android/app/build/outputs/apk/release/app-release.apk
          retention-days: 3
